"""added User Token Model

Revision ID: 1366b0e10283
Revises: 9f7b1828f141
Create Date: 2021-09-05 11:41:46.006733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1366b0e10283'
down_revision = '9f7b1828f141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('auth_token', sa.Text(), nullable=True),
    sa.Column('source_origin', sa.Integer(), nullable=True),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_tokens_created_at'), 'user_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_tokens_updated_at'), 'user_tokens', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tokens_updated_at'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_created_at'), table_name='user_tokens')
    op.drop_table('user_tokens')
    # ### end Alembic commands ###
